### ISSUE TITLE
Storage does not work when switching monitors

### ISSUE THREAD

**Issue by joshglazer** [sushinpv/react-secure-storage#14]
If I use `secureLocalStorage.setItem` on one monitor, and then move my browser to a different monitor when `secureLocalStorage.getItem` is called, the value is not retrieved from storage.   I assume this is because of the code in `fingerprint.lib.ts` as a few of the values in the `getFingerprint()` function rely on monitor settings.  Would it be possible to either remove or add an option to disable the settings that can change between monitors?

**Comment by vukvukovich** [comment]
I could not replicate this one. This is how I tested it: 

Created two buttons GET & SET and I was trying to change monitors accordingly. 
```
<button onClick={() => {secureLocalStorage.setItem("foo", 'bar');}}>SET</button>
<button onClick={() => {console.log('secureLocalStorage.setItem;', secureLocalStorage.getItem("foo"))}}>GET</button>
```

**Comment by sushinpv** [comment]
@joshglazer First of all, sorry for the delayed response. 

We are using different browser properly to create fingure print for each browser, here the recommendation is to add as much more field as possible so that the uniqueness of the hash is more,

However I have understood your concern and we can add a .env parameter for disabling browser window check. This feature will be releasing on the next release

**Comment by sushinpv** [comment]
@vukvukovich Hi, really appreciate your efforts for answering and thank you for making this community stronger. 

FYI, This issue will only come when you have two monitor with two different screen size and when you SET data from one screen and refresh the website on the other screen before GETTING the data

**Comment by joshglazer** [comment]
Thanks for taking a look @sushinpv ! I'm looking forward to the next release.

Also thanks @vukvukovich for taking a look too, and sending feedback.

**Comment by sushinpv** [comment]
@joshglazer FYI , The next release is scheduled for 26th March, You can except it by 26 or on before that

**Comment by sushinpv** [comment]
Hi @joshglazer We have related a new version called 1.2.0, Now you can disable individual browser properties 

To answer your question, You can use 

    SECURE_LOCAL_STORAGE_DISABLED_KEYS=ScreenPrint
or
    REACT_APP_SECURE_LOCAL_STORAGE_DISABLED_KEYS=ScreenPrint

**Comment by Souvikjr** [comment]
Getting null value from securelocalstorage after chrome update.


After saving some data in localstorage using securelocalstorage it's working perfectly but when the chrome is getting updated it's returning null value. Although the data is saved in local storage i can see the data from application tab of console. How to solve that.

**Comment by AustineA** [comment]
> Getting null value from securelocalstorage after chrome update.
> 
> After saving some data in localstorage using securelocalstorage it's working perfectly but when the chrome is getting updated it's returning null value. Although the data is saved in local storage i can see the data from application tab of console. How to solve that.

Yeah i'm having similar issue
