### ISSUE TITLE
TypeError: Cannot read property 'colorDepth' of undefined, js engine: hermes

### ISSUE THREAD

**Issue by agieocean** [sushinpv/react-secure-storage#15]
Version:
`"react-secure-storage": "^1.1.0"`
`"react-native": "0.71.3"`

Expected behavior: set and get two values

Actual behavior:
```
 ERROR  TypeError: Cannot read property 'colorDepth' of undefined, js engine: hermes
```

Code:
```
useEffect(() => {
        secureLocalStorage.setItem("acccess_token", response.data.access);
        secureLocalStorage.setItem("refresh-token", response.data.refresh);
        let value = secureLocalStorage.getItem("access-token");
        alert(value);
      }, []);
```

**Comment by agieocean** [comment]
Actually this error is coming from the line `import secureLocalStorage from "react-secure-storage"`

**Comment by sushinpv** [comment]
Hi @agieocean, I think you are using this library on react-native, This library is designed for web not for native mobile. 


You can use SecureStore Library for react native, Please find more information here https://docs.expo.dev/versions/latest/sdk/securestore/
