### ISSUE TITLE
Inconsistency between key of SecureLocalStorage.setItem and SecureLocalStorage.removeItem

### ISSUE THREAD

**Issue by mcuongvu28** [sushinpv/react-secure-storage#2]
If I use SecureLocalStorage.setItem to store data (as string) with 'token' key then the actual key create in local storage is '@secure.s.token'.
But when I call SecureLocalStorage.removeItem to remove 'token' key it actual remove '@secure.token' key instead.

I look to repo code and found this problem.
Please fix it!

**Comment by sushinpv** [comment]
Thanks for reporting the issue, 

Let me have a look and update accordingly

**Comment by sushinpv** [comment]
This issue has been resolved in the latest release v1.0.18
