### ISSUE TITLE
Vite support

### ISSUE THREAD

**Issue by jayantamadhav** [sushinpv/react-secure-storage#21]
The ENV vars in React projects developed using Vite has a prefix "VITE_" like "REACT_APP_" for create-react-app. 

Would love it if you could add support for Vite

**Comment by sushinpv** [comment]
Hi @jayantamadhav Sure, We can do that, 

The next release is scheduled for this weekend, You can expect these changes

**Comment by jayantamadhav** [comment]
Created a PR [https://github.com/sushinpv/react-secure-storage/pull/22](https://github.com/sushinpv/react-secure-storage/pull/22) for this.


Suggestion: 

Allow the users to pass an optional param called `HASH_KEY` in getItem() and setItem() which will override the keys fetched from .envs if provided. If not provided then look for keys in .envs. This way you don't have to deal or add support for every  new tool or framework which requires env vars to start with certain prefixes.

**Comment by sushinpv** [comment]
@jayantamadhav , Thanks for the PR and the suggestion, this might looks like a small thing to do, but if you think from the system standpoint, then in some large applications there can be more than 100s of get and set function calls, and sending these values for each and every call is not an elegant way,

We can surely think about some other way of doing the same.

+ If we keep it on .env, then its better to create different hash key for your staging, development and production environment, also this hash key just used as an add on layer, they final key which is used to encrypt the system will be a combination of your system / browser fingerprint + hash key

**Comment by sushinpv** [comment]
New version is released with the support for VITE_ and NEXT_PUBLIC_
