### ISSUE TITLE
Error when testing with jest

### ISSUE THREAD

**Issue by GlennOnyango** [sushinpv/react-secure-storage#28]
When I try to run my test I get the error below.
![Error](https://github.com/sushinpv/react-secure-storage/assets/45517989/16d80b0c-b06e-466a-bec3-5973163856e8)

**Comment by sushinpv** [comment]
@GlennOnyango This is a duplicate issue and the solution is already discussed here, 

Please refer this link https://github.com/sushinpv/react-secure-storage/issues/12
