### ISSUE TITLE
I see the value of REACT_APP_SECURE_LOCAL_STORAGE_PREFIX in the local storage

### ISSUE THREAD

**Issue by pierroberto** [sushinpv/react-secure-storage#44]
Hi team, 

I have a question about this key: `REACT_APP_SECURE_LOCAL_STORAGE_PREFIX`.

When I add `REACT_APP_SECURE_LOCAL_STORAGE_PREFIX` in my `.env`, let's say with the value of `foo`, is it correct to see in the local storage the key saved with this format: `foo.{randomCharacter}}.{myKey}`.

I'm not sure that this it is correct and I can't get answer from the documentation.

Thank you

**Comment by sushinpv** [comment]
@pierroberto This is the accurate comprehension. 

The way the libraries generate the key by default is as follows:

`secure.{data-type}.{key}`

The REACT_APP_SECURE_LOCAL_STORAGE_PREFIX is used to customize the `secure` prefix
